---
name: black_format

'on':
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  black_format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@25.1.0
        with:
          options: "--check --verbose"
