---
name: black_format

'on':
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  black_format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@24.10.0
        with:
          options: "--check --verbose"
